name: CI Pipeline & Docker Build (Advanced)

on: [push]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Dependencies
        run: pip install mlflow==2.19.0 pandas scikit-learn dagshub matplotlib

      - name: Train Model
        run: |
          cd Workflow_CI/MLProject
          python modelling.py

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
        run: |
          cd Workflow_CI/MLProject
          
          # Ambil Run ID dari file txt yang dibuat modelling.py
          RUN_ID=$(cat last_run_id.txt)
          echo "Building Docker Image for Run ID: $RUN_ID"
          
          # Command Build Docker MLflow
          mlflow models build-docker \
            -m "runs:/$RUN_ID/model" \
            -n "$DOCKER_USER/heart-disease-model:latest" \
            --enable-mlserver
          
          # Push ke Docker Hub
          docker push "$DOCKER_USER/heart-disease-model:latest"